theme: jekyll-theme-midnight
description: "Здесь расположены лабораторные работы, инвариантные и вариативные задания, выполненные в 3 - 7 семестрах, на дисциплине Программирование."
email: "vektoririnaaa@gmail.com"
title: Портфолио
author: Сорокина Ирина
