theme: jekyll-theme-midnight
baseurl: https://vektoririna.github.io/
description: "Здесь расположены лабораторные работы, инвариантные и вариативные задания, выполненные в 3 - 6 семестрах, на дисциплине Программирование."
email: "vektoririnaaa@gmail.com"
